## Numpy

Импортировать NumPy под именем np

In [2]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [4]:
vector = np.zeros(10)
vector

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

Создать вектор размера 10, заполненный единицами

In [7]:
vector = np.array([1]*10)
vector

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Создать вектор размера 10, заполненный числом 2.5

In [13]:
vector = np.ones(10)
vector

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [9]:
vector = np.zeros(10)
vector[4] = 1
vector

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

Развернуть вектор (первый становится последним)

In [18]:
vector = np.arange(0, 100, 10)
vector = vector[::-1]
vector

array([90, 80, 70, 60, 50, 40, 30, 20, 10,  0])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [23]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [58]:
import math
array = np.array([1,2,0,0,4,0])
print(list(x for x in range(array.size) if array[x]))

[0, 1, 4]


Создать 3x3 единичную матрицу

In [3]:
matrix = np.identity((3))
matrix

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

Создать массив 3x3x3 со случайными значениями

In [4]:
import random
nArray = np.array([random.randint(1,100) for _ in range(3*3*3)]).reshape(3,3,3)

nArray

array([[[80, 50, 83],
        [30,  9, 39],
        [55, 28, 12]],

       [[54, 67, 91],
        [44, 45,  9],
        [99, 51, 72]],

       [[41, 92, 47],
        [27, 17, 92],
        [45, 50,  8]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [63]:
vector = np.random.random(30)
print(vector, vector.mean())

[ 0.90424085  0.31715138  0.75176349  0.41156672  0.19953173  0.76760501
  0.10831618  0.61337698  0.99599487  0.4613391   0.95787736  0.73672253
  0.54943128  0.89591991  0.19187578  0.5492002   0.83483574  0.64890324
  0.84784938  0.93858731  0.59964124  0.08935666  0.56500815  0.15451937
  0.5361164   0.34672052  0.58859516  0.8759994   0.66108402  0.30922863] 0.580278620175


Перемножить матрицы 5x3 и 3x2

In [67]:
matrix1 = np.random.random((5,3))
matrix2 = np.random.random((3,2))

print(np.dot(matrix1, matrix2))

[[ 0.48791028  0.58900873]
 [ 0.82670962  0.89189448]
 [ 1.08463949  1.06866563]
 [ 0.64145208  0.59402713]
 [ 0.19866666  0.25573428]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [69]:
vector = np.linspace(0, 1, 12)[1:-1]
vector

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

Заменить максимальный элемент на ноль

In [70]:
vector[vector.argmax()] = 0
vector

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.        ])

Преобразовать массив из float в int

In [76]:
vector = np.eye(4)
vector = vector.astype(np.int32)
vector

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [79]:
import scipy.spatial as ss
vector = np.random.random((10,2))
distance = ss.distance.cdist(vector, vector)

print(vector, distance)

[[ 0.96447179  0.08232503]
 [ 0.33657353  0.0494376 ]
 [ 0.83427313  0.01089019]
 [ 0.20870531  0.75039678]
 [ 0.19455477  0.287081  ]
 [ 0.21079364  0.17267982]
 [ 0.19623596  0.31535639]
 [ 0.59019062  0.29100291]
 [ 0.8403104   0.50791189]
 [ 0.8130376   0.41594538]] [[ 0.          0.62875894  0.14850801  1.00871346  0.79667887  0.75907493
   0.80280128  0.42852404  0.44332858  0.36638075]
 [ 0.62875894  0.          0.49919013  0.71252652  0.276846    0.17609437
   0.30067829  0.35025051  0.68113838  0.60112059]
 [ 0.14850801  0.49919013  0.          0.96860988  0.69679332  0.64412931
   0.70695905  0.37153655  0.49705837  0.40561146]
 [ 1.00871346  0.71252652  0.96860988  0.          0.46353182  0.57772073
   0.43521905  0.59713798  0.67655296  0.69070635]
 [ 0.79667887  0.276846    0.69679332  0.46353182  0.          0.11554795
   0.02832533  0.39565528  0.68247096  0.63176502]
 [ 0.75907493  0.17609437  0.64412931  0.57772073  0.11554795  0.
   0.14341733  0.3974197   0.71321237 

Случайно расположить p элементов в 2D массив

In [84]:
p = 6
matrix = np.zeros((10,10))
np.put(matrix, np.random.choice(range(10*10), p, replace=False), 1)
matrix = matrix.astype(np.int32)
matrix 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 1, 0]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [99]:
vector = np.arange(1, 6)
zero = 3

vector1 = np.zeros(len(vector) + (len(vector)-1) * zero)
vector1[::zero+1] = vector
vector1

array([ 1.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  3.,  0.,  0.,
        0.,  0.,  4.,  0.,  0.,  0.,  0.,  5.])

Найти наиболее частое значение в массиве

In [103]:
vector = np.random.randint(0,10,50)
print(vector, np.bincount(vector).argmax())

[0 6 0 3 3 6 5 1 3 1 7 7 0 8 2 0 5 4 9 2 7 4 3 2 2 6 9 4 1 7 7 6 5 0 3 3 1
 9 0 3 2 6 2 1 4 7 3 4 5 7] 3


Найти n наибольших значений в массиве

In [104]:
vector = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (vector[np.argpartition(-vector,n)[:n]])

[9995 9999 9998 9997 9996]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [5]:
from pandas import read_csv
food = read_csv("en.openfoodfacts.org.products.tsv", '\t')

D:\ProgramFiles\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Посмотреть первые 5 записей

In [7]:
food.head()

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>code</th>
      <th>url</th>
      <th>creator</th>
      <th>created_t</th>
      <th>created_datetime</th>
      <th>last_modified_t</th>
      <th>last_modified_datetime</th>
      <th>product_name</th>
      <th>generic_name</th>
      <th>quantity</th>
      <th>...</th>
      <th>fruits-vegetables-nuts_100g</th>
      <th>fruits-vegetables-nuts-estimate_100g</th>
      <th>collagen-meat-protein-ratio_100g</th>
      <th>cocoa_100g</th>
      <th>chlorophyl_100g</th>
      <th>carbon-footprint_100g</th>
      <th>nutrition-score-fr_100g</th>
      <th>nutrition-score-uk_100g</th>
      <th>glycemic-index_100g</th>
      <th>water-hardness_100g</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>3087</td>
      <td>http://world-en.openfoodfacts.org/product/0000...</td>
      <td>openfoodfacts-contributors</td>
      <td>1474103866</td>
      <td>2016-09-17T09:17:46Z</td>
      <td>1474103893</td>
      <td>2016-09-17T09:18:13Z</td>
      <td>Farine de blé noir</td>
      <td>NaN</td>
      <td>1kg</td>
      <td>...</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>1</th>
      <td>4530</td>
      <td>http://world-en.openfoodfacts.org/product/0000...</td>
      <td>usda-ndb-import</td>
      <td>1489069957</td>
      <td>2017-03-09T14:32:37Z</td>
      <td>1489069957</td>
      <td>2017-03-09T14:32:37Z</td>
      <td>Banana Chips Sweetened (Whole)</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>...</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>14.0</td>
      <td>14.0</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2</th>
      <td>4559</td>
      <td>http://world-en.openfoodfacts.org/product/0000...</td>
      <td>usda-ndb-import</td>
      <td>1489069957</td>
      <td>2017-03-09T14:32:37Z</td>
      <td>1489069957</td>
      <td>2017-03-09T14:32:37Z</td>
      <td>Peanuts</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>...</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3</th>
      <td>16087</td>
      <td>http://world-en.openfoodfacts.org/product/0000...</td>
      <td>usda-ndb-import</td>
      <td>1489055731</td>
      <td>2017-03-09T10:35:31Z</td>
      <td>1489055731</td>
      <td>2017-03-09T10:35:31Z</td>
      <td>Organic Salted Nut Mix</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>...</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>12.0</td>
      <td>12.0</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4</th>
      <td>16094</td>
      <td>http://world-en.openfoodfacts.org/product/0000...</td>
      <td>usda-ndb-import</td>
      <td>1489055653</td>
      <td>2017-03-09T10:34:13Z</td>
      <td>1489055653</td>
      <td>2017-03-09T10:34:13Z</td>
      <td>Organic Polenta</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>...</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
<p>5 rows × 163 columns</p>
</div>

Сколько наблюдений в наборе данных?


In [10]:
food.shape

(356027, 163)

Сколько столбцов в наборе данных?

In [22]:
len(food.columns)

163

Напечатайте все названия столбцов

In [31]:
", ".join(list(food.columns.values))

'code, url, creator, created_t, created_datetime, last_modified_t, last_modified_datetime, product_name, generic_name, quantity, packaging, packaging_tags, brands, brands_tags, categories, categories_tags, categories_en, origins, origins_tags, manufacturing_places, manufacturing_places_tags, labels, labels_tags, labels_en, emb_codes, emb_codes_tags, first_packaging_code_geo, cities, cities_tags, purchase_places, stores, countries, countries_tags, countries_en, ingredients_text, allergens, allergens_en, traces, traces_tags, traces_en, serving_size, no_nutriments, additives_n, additives, additives_tags, additives_en, ingredients_from_palm_oil_n, ingredients_from_palm_oil, ingredients_from_palm_oil_tags, ingredients_that_may_be_from_palm_oil_n, ingredients_that_may_be_from_palm_oil, ingredients_that_may_be_from_palm_oil_tags, nutrition_grade_uk, nutrition_grade_fr, pnns_groups_1, pnns_groups_2, states, states_tags, states_en, main_category, main_category_en, image_url, image_small_url, en

Какое название у 105 столбца?

In [30]:
food.columns[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [38]:
food[food.columns[104]].dtype

dtype('float64')

Как проиндексирован набор данных?

In [41]:
food.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [8]:
food.iloc[18]["product_name"]

'Lotus Organic Brown Jasmine Rice'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [3]:
from pandas import read_csv
chipo = read_csv("chipotle.tsv", '\t')

Как много продуктов стоят более чем $10.00?

In [58]:
chipo['item_price_float'] = chipo['item_price']
chipo.item_price_float = chipo.item_price_float.str[1:].astype(float)
chipo[chipo.item_price_float > 10] 

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>order_id</th>
      <th>quantity</th>
      <th>item_name</th>
      <th>choice_description</th>
      <th>item_price</th>
      <th>item_price_int</th>
      <th>item_price_float</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>4</th>
      <td>2</td>
      <td>2</td>
      <td>Chicken Bowl</td>
      <td>[Tomatillo-Red Chili Salsa (Hot), [Black Beans...</td>
      <td>$16.98</td>
      <td>16.98</td>
      <td>16.98</td>
    </tr>
    <tr>
      <th>5</th>
      <td>3</td>
      <td>1</td>
      <td>Chicken Bowl</td>
      <td>[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...</td>
      <td>$10.98</td>
      <td>10.98</td>
      <td>10.98</td>
    </tr>
    <tr>
      <th>7</th>
      <td>4</td>
      <td>1</td>
      <td>Steak Burrito</td>
      <td>[Tomatillo Red Chili Salsa, [Fajita Vegetables...</td>
      <td>$11.75</td>
      <td>11.75</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>13</th>
      <td>7</td>
      <td>1</td>
      <td>Chicken Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...</td>
      <td>$11.25</td>
      <td>11.25</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>23</th>
      <td>12</td>
      <td>1</td>
      <td>Chicken Burrito</td>
      <td>[[Tomatillo-Green Chili Salsa (Medium), Tomati...</td>
      <td>$10.98</td>
      <td>10.98</td>
      <td>10.98</td>
    </tr>
    <tr>
      <th>39</th>
      <td>19</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Roasted Chili Corn Salsa, [Fajita Vegetables,...</td>
      <td>$11.75</td>
      <td>11.75</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>42</th>
      <td>20</td>
      <td>1</td>
      <td>Chicken Bowl</td>
      <td>[Roasted Chili Corn Salsa, [Rice, Black Beans,...</td>
      <td>$11.25</td>
      <td>11.25</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>43</th>
      <td>20</td>
      <td>1</td>
      <td>Steak Burrito</td>
      <td>[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...</td>
      <td>$11.75</td>
      <td>11.75</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>45</th>
      <td>21</td>
      <td>1</td>
      <td>Chicken Burrito</td>
      <td>[Tomatillo-Red Chili Salsa (Hot), [Black Beans...</td>
      <td>$10.98</td>
      <td>10.98</td>
      <td>10.98</td>
    </tr>
    <tr>
      <th>52</th>
      <td>24</td>
      <td>1</td>
      <td>Chicken Burrito</td>
      <td>[Roasted Chili Corn Salsa (Medium), [Black Bea...</td>
      <td>$10.98</td>
      <td>10.98</td>
      <td>10.98</td>
    </tr>
    <tr>
      <th>57</th>
      <td>26</td>
      <td>1</td>
      <td>Veggie Burrito</td>
      <td>[Tomatillo Red Chili Salsa, [Fajita Vegetables...</td>
      <td>$11.25</td>
      <td>11.25</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>58</th>
      <td>27</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Roasted Chili Corn Salsa, [Fajita Vegetables,...</td>
      <td>$11.75</td>
      <td>11.75</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>62</th>
      <td>28</td>
      <td>1</td>
      <td>Veggie Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...</td>
      <td>$11.25</td>
      <td>11.25</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>68</th>
      <td>30</td>
      <td>1</td>
      <td>Chicken Burrito</td>
      <td>[Tomatillo-Red Chili Salsa (Hot), [Black Beans...</td>
      <td>$10.98</td>
      <td>10.98</td>
      <td>10.98</td>
    </tr>
    <tr>
      <th>79</th>
      <td>35</td>
      <td>1</td>
      <td>Chicken Soft Tacos</td>
      <td>[Roasted Chili Corn Salsa, [Rice, Cheese, Lett...</td>
      <td>$11.25</td>
      <td>11.25</td>
      <td>11.25</td>
    </tr>
    

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [62]:
chipo.loc[:,['item_name','item_price']]

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>item_name</th>
      <th>item_price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Chips and Fresh Tomato Salsa</td>
      <td>$2.39</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Izze</td>
      <td>$3.39</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Nantucket Nectar</td>
      <td>$3.39</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Chips and Tomatillo-Green Chili Salsa</td>
      <td>$2.39</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Chicken Bowl</td>
      <td>$16.98</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Chicken Bowl</td>
      <td>$10.98</td>
    </tr>
    <tr>
      <th>6</th>
      <td>Side of Chips</td>
      <td>$1.69</td>
    </tr>
    <tr>
      <th>7</th>
      <td>Steak Burrito</td>
      <td>$11.75</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Steak Soft Tacos</td>
      <td>$9.25</td>
    </tr>
    <tr>
      <th>9</th>
      <td>Steak Burrito</td>
      <td>$9.25</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Chips and Guacamole</td>
      <td>$4.45</td>
    </tr>
    <tr>
      <th>11</th>
      <td>Chicken Crispy Tacos</td>
      <td>$8.75</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Chicken Soft Tacos</td>
      <td>$8.75</td>
    </tr>
    <tr>
      <th>13</th>
      <td>Chicken Bowl</td>
      <td>$11.25</td>
    </tr>
    <tr>
      <th>14</th>
      <td>Chips and Guacamole</td>
      <td>$4.45</td>
    </tr>
    <tr>
      <th>15</th>
      <td>Chips and Tomatillo-Green Chili Salsa</td>
      <td>$2.39</td>
    </tr>
    <tr>
      <th>16</th>
      <td>Chicken Burrito</td>
      <td>$8.49</td>
    </tr>
    <tr>
      <th>17</th>
      <td>Chicken Burrito</td>
      <td>$8.49</td>
    </tr>
    <tr>
      <th>18</th>
      <td>Canned Soda</td>
      <td>$2.18</td>
    </tr>
    <tr>
      <th>19</th>
      <td>Chicken Bowl</td>
      <td>$8.75</td>
    </tr>
    <tr>
      <th>20</th>
      <td>Chips and Guacamole</td>
      <td>$4.45</td>
    </tr>
    <tr>
      <th>21</th>
      <td>Barbacoa Burrito</td>
      <td>$8.99</td>
    </tr>
    <tr>
      <th>22</th>
      <td>Nantucket Nectar</td>
      <td>$3.39</td>
    </tr>
    <tr>
      <th>23</th>
      <td>Chicken Burrito</td>
      <td>$10.98</td>
    </tr>
    <tr>
      <th>24</th>
      <td>Izze</td>
      <td>$3.39</td>
    </tr>
    <tr>
      <th>25</th>
      <td>Chips and Fresh Tomato Salsa</td>
      <td>$2.39</td>
    </tr>
    <tr>
      <th>26</th>
      <td>Chicken Bowl</td>
      <td>$8.49</td>
    </tr>
    <tr>
      <th>27</th>
      <td>Carnitas Burrito</td>
      <td>$8.99</td>
    </tr>
    <tr>
      <th>28</th>
      <td>Canned Soda</td>
      <td>$1.09</td>
    </tr>
    <tr>
      <th>29</th>
      <td>Chicken Burrito</td>
      <td>$8.49</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>4592</th>
      <td>Barbacoa Burrito</td>
      <td>$11.75</td>
    </tr>
    <tr>
      <th>4593</th>
      <td>Carnitas Bowl</td>
      <td>$11.75</td>
    </tr>
    <tr>
      <th>4594</th>
      <td>Barbacoa Bowl</td>
      <td>$11.75</td>
    </tr>
    <tr>
      <th>4595</th>
      <td>Chicken Bowl</td>
      <td>$8.75</td>
    </tr>
    <tr>
      <th>4596</th>
      <td>Chips and Guacamole</td>
      <td>$4.45</td>
    </tr>
    <tr>
      <th>4597</th>
      <td>Canned Soft Drink</td>
      <td>$1.25</td>
    </tr>
    <tr>
      <th>4598</th>
      <td>Bottled Water</td>
      <td>$1.50</td>
    </tr>
    <tr>
      <th>4599</th>
      <td>Chicken Bowl</td>
      <td>$8.75</td>
    </tr>
    <tr>
      <th>4600</th>
      <td>Chips and Guacamole</td>
      <td>$4.45</td>
   

Отсортировать по имени предмета

In [4]:
chipo.sort_values(by=['item_name'])

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description item_price  
3389                                        [Diet Coke]    $12.98   
341                                         [Diet Coke]     $6.49   
1849                                             [Coke]     $6.49   
1860                                        [Diet Coke]     $6.49   
2713                                             [Coke]     $6.49   
3422                                             [Coke]     $6.49   
553                                         [Diet Coke]     $6.49   
1916                                        [Diet Coke]     $6.49   
1922                                             [Coke]     $6.49   
1937                                        [Diet Coke]     $6.49   
3836                                             [Coke]     $6.49   
298                                            [Sprite]     $6.49   
1976                                        [Diet Coke]     $6.49   
1167                                             [Coke]     $6.49   
3875                                        [Diet Coke] 

Сколько было заказано самого дорогого предмета?

In [40]:
chipo.loc[chipo['item_name'] == chipo.sort_values(by=["item_price"]).tail(1)["item_name"].values[0]].groupby('item_name')['quantity'].sum()[0]

130

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [30]:
len(chipo.loc[chipo['item_name'] == "Veggie Salad Bowl"].index)

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [49]:
len(chipo.loc[(chipo['item_name'] == "Canned Soda") & (chipo["quantity"] > 1)].index)


20